### ISSUE TITLE
Take information which CVEs are closed by patches in distros

### ISSUE THREAD

**Issue by mikhailnov** [repology/repology-vulnupdater#10]
Hello.
https://repology.org/projects/?inrepo=rosa_2019_1&vulnerable=1 is a nice feed and could be useful in distro development, but many CVEs are fixed by attaching a patch.
If a distro provides machine-readable information which CVEs are fixed in package version higher than X, would repology be able to use it?

**Comment by mikhailnov** [comment]
FreeBSD provides such information: https://vuxml.freebsd.org/freebsd/index-cve.html
We in ROSA could also create something like that both for internal and public use.]
ALT Linux, as far as I know, has such an database, maybe it is not public and they could publish such metainformation.

**Comment by AMDmi3** [comment]
Duplicate of https://github.com/repology/repology-updater/issues/1045.
